In [10]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv('Companies-House-search-results.csv')
data.head()

,company_name,company_number,company_status,company_type,company_subtype,dissolution_date,incorporation_date,removed_date,registered_date,nature_of_business,registered_office_address
0,ANIMAL MEDICINES TRAINING REGULATORY AUTHORITY...,02140832,Active,Private limited by guarantee without share cap...,NaN,NaN,1987-06-18,NaN,NaN,75000 84120,Unit 1c Windmill Avenue Woolpit Business Park ...
1,GBM AUTHORISED REPRESENTATIVE LIMITED,03916444,Active,Private limited company,NaN,NaN,2000-01-31,NaN,NaN,84120,The White House 2 Meadrow Godalming GU7 3HN
2,WESTGATE SAFETY & TRAINING LIMITED,05207326,Active,Private limited company,NaN,NaN,2004-08-16,NaN,NaN,84120,Bredbury Parkway Bredbury Park Way Bredbury Pa...
3,BIRMINGHAM LGBT,07203554,Active,Private Limited Company by guarantee without s...,NaN,NaN,2010-03-25,NaN,NaN,84120 96090,"38/40 Holloway Circus, Queensway Birmingham B1..."
4,TRURO PHYSIOTHERAPY LIMITED,09194419,Active,Private limited company,NaN,NaN,2014-08-29,NaN,NaN,84120,48 Arwenack Street Falmouth TR11 3JH

In [12]:
data.shape

(5000, 11)

In [14]:
x = data.loc[data['registered_office_address'] == 'KT3']

In [16]:
print (x)

Empty DataFrame
Columns: [company_name, company_number, company_status, company_type, company_subtype, dissolution_date, incorporation_date, removed_date, registered_date, nature_of_business, registered_office_address]
Index: []

In [9]:
y.shape

(32,)

In [10]:
z = x.iloc[0:1350,6:7].value_counts()
print(z)

LOCALAUTHORITY
London Borough of Croydon Council                   127
London Borough of Barnet Council                     83
London Borough of Redbridge Council                  82
London Borough of Enfield Council                    81
London Borough of Sutton Council                     78
London Borough of Brent Council                      58
London Borough of Havering Council                   57
London Borough of Lewisham Council                   56
London Borough of Harrow Council                     55
London Borough of Bromley Council                    53
London Borough of Waltham Forest Council             49
London Borough of Hillingdon Council                 47
London Borough of Ealing Council                     46
London Borough of Richmond upon Thames Council       44
London Borough of Lambeth Council                    44
London Borough of Greenwich Council                  43
Royal Borough of Kingston upon Thames Council        38
London Borough of Merton Council                     37
London Borough of Haringey Council                   32
London Borough of Wandsworth Council                 30
London Borough of Bexley Council                     30
London Borough of Hounslow Council                   30
London Borough of Newham Council                     27
London Borough of Barking and Dagenham Council       22
London Borough of Southwark Council                  19
London Borough of Islington Council                  16
London Borough of Hackney Council                    15
Royal Borough of Kensington and Chelsea Council      11
Westminster City Council                             11
London Borough of Tower Hamlets Council              10
London Borough of Camden Council                     10
London Borough of Hammersmith and Fulham Council      9
dtype: int64

In [11]:
z.shape

(32,)

In [12]:
w = data.loc[data['DISTRICT'] == 'Hammersmith & Fulham Borough']
print(w)

       Ref_ID  Company ID  COUNTRY  REGION  COUNTY  \
1822     4990         NaN  England  London  London
6048    15858         NaN  England  London  London
8607    27084         NaN  England  London  London
10695   35510         NaN  England  London  London
11250   40118         NaN  England  London  London
11251   40119         NaN  England  London  London
12403   47597         NaN  England  London  London
12721   51696         NaN  England  London  London
12992   52831         NaN  England  London  London

                           DISTRICT  \
1822   Hammersmith & Fulham Borough
6048   Hammersmith & Fulham Borough
8607   Hammersmith & Fulham Borough
10695  Hammersmith & Fulham Borough
11250  Hammersmith & Fulham Borough
11251  Hammersmith & Fulham Borough
12403  Hammersmith & Fulham Borough
12721  Hammersmith & Fulham Borough
12992  Hammersmith & Fulham Borough

                                         LOCALAUTHORITY  \
1822   London Borough of Hammersmith and Fulham Council
6048   London Borough of Hammersmith and Fulham Council
8607   London Borough of Hammersmith and Fulham Council
10695  London Borough of Hammersmith and Fulham Council
11250  London Borough of Hammersmith and Fulham Council
11251  London Borough of Hammersmith and Fulham Council
12403  London Borough of Hammersmith and Fulham Council
12721  London Borough of Hammersmith and Fulham Council
12992  London Borough of Hammersmith and Fulham Council

                              FULLNAME                      MAILINGNAME  \
1822                       Cambuslodge                      Cambuslodge
6048      Nazareth House - Hammersmith     Nazareth House - Hammersmith
8607                     Richford Gate                    Richford Gate
10695      The Chiswick Nursing Centre      The Chiswick Nursing Centre
11250                     Harwood Road                     Harwood Road
11251                    Talgarth Road                    Talgarth Road
12403                        Farm Lane                        Farm Lane
12721                St Vincents House                St Vincents House
12992  Rivercourt Project Short Breaks  Rivercourt Project Short Breaks

                         ADDRESS1  ... PROPERTYPURPOSEBUILT  \
1822   151 Wandsworth Bridge Road  ...                    N
6048     169/175 Hammersmith Road  ...                  NaN
8607          52/53 Richford Gate  ...                  NaN
10695         Ravenscourt Gardens  ...                    Y
11250          95/99 Harwood Road  ...                  NaN
11251       41 - 43 Talgarth Road  ...                  NaN
12403             17/25 Farm Lane  ...                    Y
12721    49 Queen Caroline Street  ...                    Y
12992          17 Rivercourt Road  ...                  NaN

      FIRSTYEARASCAREHOME YEAROFLASTMAJORCONVERSION  \
1822               1988.0                    2016.0
6048                  0.0                       NaN
8607                  NaN                       NaN
10695              1999.0                    2016.0
11250                 0.0                       NaN
11251                 0.0                       NaN
12403                 0.0                    2011.0
12721                 0.0                    2009.0
12992                 NaN                       NaN

      INDUSTRIALWASHINGMACHINEON_SITE AGEFROM  AGETO NOOFBEDSPRIVATELYFUNDED  \
1822                                Y    18.0    NaN                     NaN
6048                              NaN    65.0    NaN                     NaN
8607                              NaN     NaN    NaN                     NaN
10695                             NaN    18.0  105.0                     NaN
11250                             NaN    18.0    NaN                     NaN
11251                             NaN    18.0    NaN                     NaN
12403                             NaN    55.0    NaN                     NaN
12721                             NaN    55.0    NaN                     NaN
12992                             NaN     NaN    NaN                     NaN

             OPEN_STATUS LATITUDE LONGITUDE
1822   Open / Registered  51.4714 -0.191076
6048   Open / Registered  51.4929 -0.218835
8607   Open / Registered  51.4998 -0.226446
10695  Open / Registered  51.4957 -0.242613
11250  Open / Registered  51.4780 -0.192599
11251  Open / Registered  51.4902 -0.209675
12403  Open / Registered  51.4823 -0.196478
12721  Open / Registered  51.4907 -0.224423
12992  Open / Registered  51.4921 -0.236095

[9 rows x 116 columns]

In [16]:
data.drop(['Company ID'], axis=1)

,Ref_ID,COUNTRY,REGION,COUNTY,DISTRICT,LOCALAUTHORITY,FULLNAME,MAILINGNAME,ADDRESS1,ADDRESS2,...,PROPERTYPURPOSEBUILT,FIRSTYEARASCAREHOME,YEAROFLASTMAJORCONVERSION,INDUSTRIALWASHINGMACHINEON_SITE,AGEFROM,AGETO,NOOFBEDSPRIVATELYFUNDED,OPEN_STATUS,LATITUDE,LONGITUDE
0,2,England,Yorkshire & The Humber,South Yorkshire,Sheffield Area,Sheffield City Council,Aaron House,Aaron House,20 Collegiate Crescent,Broomhall,...,N,1992.0,2005.0,NaN,50.0,NaN,NaN,Open / Registered,53.375800,-1.488390
1,7,England,Yorkshire & The Humber,South Yorkshire,Sheffield Area,Sheffield City Council,Cairn Home,Cairn Home,58 Selborne Road,Crosspool,...,Y,NaN,2001.0,Y,NaN,NaN,NaN,Open / Registered,53.378800,-1.518810
2,9,England,Yorkshire & The Humber,South Yorkshire,Sheffield Area,Sheffield City Council,White Rose Court,White Rose Court,40/42 Clifton Avenue,Handsworth,...,NaN,1997.0,NaN,NaN,NaN,NaN,NaN,Open / Registered,53.378500,-1.398610
3,10,England,Yorkshire & The Humber,South Yorkshire,Sheffield Area,Sheffield City Council,Darwin House,Darwin House,Darwin Lane,NaN,...,N,1992.0,NaN,NaN,65.0,NaN,NaN,Open / Registered,53.375400,-1.522080
4,14,England,Yorkshire & The Humber,South Yorkshire,Sheffield Area,Sheffield City Council,Hallamshire,Hallamshire Residential Home,3 Broomhall Road,NaN,...,N,0.0,2013.0,NaN,60.0,NaN,NaN,Open / Registered,53.374600,-1.486190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17893,65432244740,England,Yorkshire & The Humber,North Lincolnshire,North Lincolnshire Area,North Lincolnshire Council,Barton House,Barton House,Tofts Road,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,Open / Registered,53.681847,-0.448382
17894,65432244744,England,South West England,Cornwall,Cornwall Area,Cornwall Council,Newport Square,Newport Square,5 Newport Square,Newport,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,Open / Registered,50.642185,-4.366169
17895,65432244835,England,Yorkshire & The Humber,West Yorkshire,Wakefield Area,City of Wakefield Metropolitan District Council,Bennett Court,Bennett Court,Ash Grove,South Elmsall,...,Y,0.0,NaN,NaN,18.0,NaN,NaN,Open / Registered,53.599236,-1.286717
17896,65432244910,England,South East England,Surrey,Woking Area,Surrey County Council,Charrington Manor Care Home,Charrington Manor Care Home,1A Hobbs Close,NaN,...,NaN,0.0,NaN,NaN,65.0,NaN,NaN,Opening 01 Feb 2022 / Not Registered,51.337630,-0.499874
17897,65432244941,England,East of England,Suffolk,Suffolk Coastal Area,Suffolk County Council,Cavell Manor Care Home,Cavell Manor Care Home,Bredfield Road,NaN,...,Y,2021.0,NaN,NaN,65.0,NaN,NaN,Open / Registered,52.102142,1.314010

NameError: name 'data' is not defined